language: csharp
mono: none
dotnet: 2.1
script:
 - dotnet restore
solution: DentalResearchApp.sln

deploy:
  provider: heroku
  api_key:
    secure: R1wdIXCwBWmC+1DU9kY1Vdrl7qTMtJZ6JB0yhtFMJyEaGd3H1Ldp8YyTgh/g7f2FYR9v3tIWnb60ZR7epmKPU3shtlUolH8bVzz0jvsKdn0WUydSbf/DsZGbX8+3d5zxt13EjdF5v7z9NFGvHfw9GXj7EpwAWYaBXr1/HPTaNEON0kAXcuXKs02227ZA6Dc9qGXvoCLoEbE2rVHlz6N+W15dueYkaBMpaCl7o9eG/qkUQ6h8xJ39oQ2djtWvISfU0iwwYY7Lw5mxZaY+nOI2XTue55qJ8ivIsCht9WFXxB6xFSmAUH74kSjK5RIGOo+LStE0pE3+WaCz5QcbMcUWuocQEBt8HfACmW1i9R97xaWeWEhnzIQFlTfV08SXv2f70XpAKUXRGB3bOohWcSg3W8S+9NZNM7N3jN3jkxiU9Q2lXWtj+SQFeWVjA4lyIlD4CiNBhobL0o1nwGfWokaicnYhvrcJO6H7jTci0F6mkdzYbkZKd5Q4o4MDbYqk8aLbJuS9uEBXQ+iTyJZtTn/BEULnc+evAXuDj/TD00lIlIWYgQIrU0IXWHocLDFFhGrfOx8hDV8sO4pqKTrKpYjNiWqjw6QB8V57BXrB1qhQ8lj0RQ8agqrPgAJcXcrkjpZ7+U2eeJf62rtaWBnGnCMXFmky4f6OO5t1dSj4TtsWDnM=
  app: bachelor2018e21
  strategy: git