language: csharp
mono: none
dotnet: 2.1
script:
- dotnet restore
solution: DentalResearchApp.sln
deploy:
  api_key:
    secure: r+ensTHPRM7SQF0Be7zBDy+KYU9UcqeLOOqg0VVEiL8CduXPuTs+GCOg0DQTy0on6eZEkEG9K7lfxVTOPuMz/volDC4ZCBJ2oHCFq8d8y7GR3QMQ7yVRpyNEVBMV9AftvDPgRe5XRrsvwuQNwRwhSp+YhqbIo6FSCNhpZMVnckZCUibDyBL5hgQJkoadMyVj5C4OVwNUL2w3Ko5GwnCnvQy15kp05vriip0rJ0BQ9zSoteKFxd7JQezHIAfnoqvzULaKIl5pfeRhzXYBmL0w+nxjL5zlQCWGlNPhM+u4r23dabIMPSOkRyHNyxqBARcv07z2k3HMEICF4RnzrNZvRR5PRS7MoqXQTdvkeHmQQXZgzeL08WQ7E5/hszl+UwOI87Epq5ah2wqzyOSqWcBIS2Agcp3bwRjILYjnROUhSJvJlwSJTigChxHgWIwcurn+7EmieNj2RgMdMMjMidYioNxt8yzZKghuucqrL5+hwKKogcjapFJcv9pf/y1LUZIzoIGnAIcT9dk/mpxJF771PqhimWOzcb27Kh6vppdiKWKcLcwOcp101eYSvLVhALP7W07yVPsR5xDgOxedxbnz7YjlJyGue0VWYt+LywqPeW4oaV1CWRnSwQx++q+wy6pP8qag+/27xipOTfaNRLTjiqZPvAE6S4mfgprHu+nb60Y=
  app: bachelor2018e21
  provider: heroku
env:
  global:
    secure: r+ensTHPRM7SQF0Be7zBDy+KYU9UcqeLOOqg0VVEiL8CduXPuTs+GCOg0DQTy0on6eZEkEG9K7lfxVTOPuMz/volDC4ZCBJ2oHCFq8d8y7GR3QMQ7yVRpyNEVBMV9AftvDPgRe5XRrsvwuQNwRwhSp+YhqbIo6FSCNhpZMVnckZCUibDyBL5hgQJkoadMyVj5C4OVwNUL2w3Ko5GwnCnvQy15kp05vriip0rJ0BQ9zSoteKFxd7JQezHIAfnoqvzULaKIl5pfeRhzXYBmL0w+nxjL5zlQCWGlNPhM+u4r23dabIMPSOkRyHNyxqBARcv07z2k3HMEICF4RnzrNZvRR5PRS7MoqXQTdvkeHmQQXZgzeL08WQ7E5/hszl+UwOI87Epq5ah2wqzyOSqWcBIS2Agcp3bwRjILYjnROUhSJvJlwSJTigChxHgWIwcurn+7EmieNj2RgMdMMjMidYioNxt8yzZKghuucqrL5+hwKKogcjapFJcv9pf/y1LUZIzoIGnAIcT9dk/mpxJF771PqhimWOzcb27Kh6vppdiKWKcLcwOcp101eYSvLVhALP7W07yVPsR5xDgOxedxbnz7YjlJyGue0VWYt+LywqPeW4oaV1CWRnSwQx++q+wy6pP8qag+/27xipOTfaNRLTjiqZPvAE6S4mfgprHu+nb60Y=
